# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1okmJKdkyx8WVObm4QxuUFED0bFAx4g5O
"""

G=1
M1=5
M2=10
m=1
x1=1
x2=(M1*x1)/M2
w=np.sqrt((M1+M2)*G/(x1+x2)**3)
def f(x, y):
    return -(G*M1*m/np.sqrt((x+x1)**(2)+y**2))-(G*M2*m/np.sqrt((x-x2)**(2)+y**2))-(m*w**(2)/2)*(x**(2)+y**(2))

x = np.linspace(-3, 3, 100)
y = np.linspace(-3, 3, 100)
X, Y = np.meshgrid(x, y)
Z = f(X, Y)
plt.contour(X,Y,Z,levels=100)
plt.show()